baseball/urls.py
from django.urls import path
from . import views

app_name = "baseball"
urlpatterns = [
    path("", views.index, name="index"),
    #path("standings", views.standings, name="standings"),
]

dejavu/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('baseball/', include('baseball.urls')),
] 

baseball/models.py
from django.db import models

# Create your models here.

baseball/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render
from datetime import datetime
from . import util

# Create your views here.
def index(request):    
    if request.method == "GET" and "date" in request.GET:  
        date_str = request.GET["date"]
        d = datetime.strptime(date_str, '%Y-%m-%d').date()
        league = request.GET["league"]
        if d < util.start_of_season():
            return render (request, "baseball/index.html", {"errormsg":"Please select a valid date, season began April 10, 1967", "datestr":"1967-04-10"})
        else:            
            if d >= util.end_of_season():
                message = util.league_name(league) + " final standings"
                final = True
            else:
                message = util.league_name(league) + " standings on " 
                final = False
            standings = util.standings(d, league)
            context = {"standings": standings, "date": d, "datestr": date_str, "message": message, "final_standings":final}
            return render(request, "baseball/index.html", context)
    else:  
        context = {"datestr": "1967-04-10"}
        return render(request, "baseball/index.html", context)

baseball/templates/baseball/index.html
{% extends "baseball/layout.html" %}  

{% block body %}
        <p>Baseball is all about the standings.
            What day and what league woud you like to know about in the 1967 season.</p>

        <form action="{% url 'baseball:index' %}" method="get" id="dateform">
            <label for="dateid">Date to view:{% if errormsg %} {{errormsg}} {% endif %}</label>
                <input type="date" id="dateid" name="date" value="{{ datestr }}" min="1967-04-01" max="1967-10-31">
                <input type="submit">
            <label for="leagues">Choose a League:</label>
                <select id="leagues" name="league" form="dateform">            
                    <option value="AL">American League</option>
                    <option value="NL">National League</option>
                </select>
        </form>
    
        {% if standings %}    
        <hr style="width: 100%"; color="gray" >
            {% include "baseball/standings.html" %}    
        
    
    {% endif %}
{% endblock %} 

baseball/templates/baseball/layout.html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <link rel="stylesheet" href="https://cdn.simplecss.org/simple.css">
        <title>Play Ball!</title>
    </head>
    <body>
        <header>
            <nav>    
                <ul>
                    <li><a href="{% url 'baseball:index' %}" id="Home">Refresh Page</a></li>
                </ul>    
            </nav>
        </header>
        {% block body %}
        {% endblock %}
    </body>
    <footer>
        <hb></hb>
        <p> Copyrigth 2022 by UAA 490</p>
    </footer>
</html>

baseball/templates/baseball/standings.html
    
     <p>
        
        {% if final_standings %}
            {{ message }}:
        {% else %}
        {{ message }} {{ date }}:
        {% endif %}    
    </p>
    <table>
        <thead>
            <th colspan="2">Team Name</th>
            <th>Wins</th>
            <th>Losses</th>
            <th>GB</th>
        </thead> 

        <tbody>
        {% for team in standings %}
        <tr>
        {% for item in team %}
        {% if forloop.counter == 2 %}
            <td><img src={{item}}></td>
            {% else %}
            <td>{{ item }}</td>
        {% endif %}
        {% endfor %}   
        </tr>
       {% endfor %}
        </tbody>
        </table>